{
 "title": "Metrics for Algo",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sorting Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Time_for_Bubble_Sort{quantile=\"0.5\",}",
     "legendFormat": "Bubble sort"
    },
    {
     "expr": "Time_for_Heap_Sort{quantile=\"0.5\",}",
     "legendFormat": "Heap sort"
    },
    {
     "expr": "Time_for_Insertion_Sort_{quantile=\"0.5\",} ",
     "legendFormat": "Insertion sort"
    },
    {
     "expr": "Time_for_Merge_Sort{quantile=\"0.5\",} ",
     "legendFormat": "Merge sort"
    },
    {
     "expr": "Time_for_Quick_Sort{quantile=\"0.5\",}",
     "legendFormat": "Quick sort"
    },
    {
     "expr": "Time_for_Radix_Sort{quantile=\"0.5\",}",
     "legendFormat": "Radix sort"
    },
    {
     "expr": "Time_for_Selection_Sort{quantile=\"0.5\",}",
     "legendFormat": "Selection sort"
    }
   ]
  },
  {
   "title": "Searching Methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "Time_for_Binary_Search{quantile=\"0.5\"}",
     "legendFormat": "Binary Search"
    },
    {
     "expr": "Time_for_Interpolation_Search{quantile=\"0.5\"}",
     "legendFormat": "Interpolation Search"
    },
    {
     "expr": "Time_for_Jump_Search{quantile=\"0.5\"}",
     "legendFormat": "Jump Search "
    },
    {
     "expr": "Time_for_Linear_Search{quantile=\"0.5\"}",
     "legendFormat": "Linear Search "
    }
   ]
  },
  {
   "title": "Data structure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "Timer_for_Stack_push{quantile=\"0.5\"}",
     "legendFormat": "Stack push"
    },
    {
     "expr": "Timer_for_Stack_pop{quantile=\"0.5\"}",
     "legendFormat": "Stack pop"
    },
    {
     "expr": "Timer_for_enqueue{quantile=\"0.5\"}",
     "legendFormat": "Enqueue"
    },
    {
     "expr": "Timer_for_dequeue{quantile=\"0.5\"}",
     "legendFormat": "Dequeue"
    }
   ]
  }
 ]
}